project:
  type: website

website:
  title: "<img src='/images/credit_card_fraud.jpeg' alt='carcrash' style='width: 1.9em; height: 1.9em; border-radius: 50%'> <b> Fraud Detection </b>"
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-S24/project-final # Need to change to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
